version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-lavrdb}
      POSTGRES_USER: ${POSTGRES_USER:-lavruser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-lavrpass}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-lavruser} -d $${POSTGRES_DB:-lavrdb} -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./backend/.env
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8000/healthz"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 20s
    restart: unless-stopped

  bot:
    build:
      context: .
      dockerfile: ./lvbot/Dockerfile
    depends_on:
      backend:
        condition: service_healthy
    env_file:
      - ./lvbot/.env
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/static
      - media_volume:/media
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pg_data:
  static_volume:
  media_volume:
