version: "3.9"

services:
  # db:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: your_db
  #     POSTGRES_USER: your_user
  #     POSTGRES_PASSWORD: your_pass
  #   volumes:
  #     - pg_data:/var/lib/postgresql/data

  # redis:
  #   image: redis:alpine

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    # depends_on:
    #   - db
    #   - redis
    volumes:
      - ./backend:/app
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - "8000"

  bot:
    build:
      context: .
      dockerfile: ./lvbot/Dockerfile
  
    environment:
      API_BASE_URL: http://backend:8000
      BOT_TOKEN: 8362762788:AAG2IVIFES7nMplxOlJTynyS9s0qPmL9MqQ
      PUBLIC_BASE_URL: http://lavrpro.ru
      LOG_LEVEL: INFO

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/static
      - media_volume:/media
    depends_on:
      - backend

volumes:
  pg_data:
  static_volume:
  media_volume:
