# Generated by Django 5.2.4 on 2025-08-02 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='preview_image',
        ),
    ]
