# Generated by Django 5.2.4 on 2025-08-03 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_brand_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='archive',
            field=models.FileField(blank=True, null=True, upload_to='brands/zips/'),
        ),
    ]
