# Generated by Django 5.2.4 on 2025-08-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_brand_archive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ('sort_order', 'name'), 'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AddField(
            model_name='brand',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
